/*
* Class: AccountDomain
* @author 
* @version
* ----------------------------------------------------------------------------------
* @description  Purpose/Methods:
*  - Contains business rules for managing accounts
*/
public class AccountDomain {
    /**
    * @description test method for demonstrating trigger framework
    * @param list of new Accounts 
    * @return null
    */  
    /*public void testDXMethod(List<Account> newAccountList) {
    }*/
}