/**
*******************************************************************************
* Class: Constants
* @author 
* @version 1.0
*
*
* ----------------------------------------------------------------------------------
* Purpose/Methods:
*  - Contains constants used in custom apex classes.  As opposed to updating many 
*    locations when an attribute or field value changes, utilize this class to define
*    contants and make centralized changes.
*
*/
public class Constants {             
      
    //SOBJECT NAMES
    //**************************************************       
    //SObjectType names
    public static final String ST_ACCOUNT = 'Account';
    
    //Eror Value
    public static final String ERROR_DUPLICATE_VALUE = 'duplicate value';
}